server.port=8082
spring.application.name=produto-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/sptech-db-mcs
spring.datasource.username=postgres
spring.datasource.password=spt1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework=DEBUG
logging.level.com.exemplo=DEBUG
